---
version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    target-branch: "production"
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      development:
        patterns:
          - "*"
        exclude-patterns:
          - "rails"
          - "sidekiq"
          - "pg"
      rails:
        patterns:
          - "rails"
      background-processing:
        patterns:
          - "sidekiq"
      database:
        patterns:
          - "pg"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    target-branch: "production"
